name = "Razor"
grammar = "razor"
path_suffixes = ["cshtml", "razor"]
line_comments = ["// "]
block_comment = ["@* ", " *@"]
autoclose_before = ";:.,=}])>"
tab_size = 4
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "<", end = ">", close = false, newline = true, not_in = ["comment", "string"] },
]
